name: Continuous Integration
on: pull_request
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up GO
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Install dependencies
        run: |
          go install ./...
          go get -u golang.org/x/lint/golint
      - name: Build
        run: env GOOS=linux GOARCH=arm GOARM=6 go build ./cmd/...
      - name: Analyze code
        run: |
          golint ./...
          go vet ./...
      - name: Test
        run: go test ./... -cover -timeout 1m